name: alihsaas
description: Sends HTTP POST data with json
author: alihsaas

inputs:
  payload:
    required: true
    description: published release event json (as string)
  personal-access-token:
    required: true
    description: personal access token used for authorization in the HTTP POST request

runs:
  using: node12
  main: dist/index.js
